# Generated by Django 3.0.7 on 2020-07-14 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0004_auto_20200714_2144'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kids',
            new_name='Kid',
        ),
        migrations.RenameModel(
            old_name='Rules',
            new_name='Rule',
        ),
    ]
