# Generated by Django 3.0.7 on 2020-08-11 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0006_kidinstance_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kidinstance',
            name='rules',
        ),
    ]
