# Generated by Django 3.0.7 on 2020-08-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0008_delete_ruleinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='completed',
            field=models.BooleanField(default=False, help_text='Is this rule completed?'),
        ),
    ]
