# Generated by Django 3.0.7 on 2020-08-13 18:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0009_rule_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this rule', primary_key=True, serialize=False)),
                ('rules', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chart.Rule')),
            ],
        ),
        migrations.DeleteModel(
            name='KidInstance',
        ),
    ]
