# Generated by Django 3.0.7 on 2020-08-13 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0010_auto_20200813_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruleinstance',
            old_name='rules',
            new_name='rule',
        ),
    ]
