# Generated by Django 3.0.7 on 2020-08-18 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0011_auto_20200813_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kid',
            name='rules',
        ),
        migrations.AddField(
            model_name='kid',
            name='rules',
            field=models.ForeignKey(help_text='Select a rule to give to this kid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chart.RuleInstance'),
        ),
    ]
