# Generated by Django 3.0.7 on 2020-08-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0012_auto_20200818_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kid',
            name='rules',
        ),
        migrations.AddField(
            model_name='kid',
            name='rules',
            field=models.ManyToManyField(help_text='Select a rule to give to this kid', to='chart.RuleInstance'),
        ),
    ]
