# Generated by Django 3.0.7 on 2020-08-26 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0013_auto_20200826_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kid',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='completed',
        ),
        migrations.AddField(
            model_name='ruleinstance',
            name='completed',
            field=models.BooleanField(default=False, help_text='Is this rule completed?'),
        ),
        migrations.AddField(
            model_name='ruleinstance',
            name='kid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='chart.Kid'),
        ),
    ]
